# fly.toml app configuration file generated for still-thunder-3495 on 2023-09-19T21:59:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-thunder-3495"
primary_region = "den"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
